apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3  ## Number of desired pod replicas
  selector:
    matchLabels:
      app: nginx  ## Label selector for pods
  template:
    metadata:
      labels:
        app: nginx  # #Labels for the pod
    spec:
      containers:
      - name: nginx
        image: nginx:1.19  ## Image of the container
        ports:
        - containerPort: 80  # Expose port 80
  strategy:
    type: RollingUpdate  # #Default strategy for updating pods
    rollingUpdate:
      maxSurge: 1  # Maximum number of extra pods during updates
      maxUnavailable: 1  # Maximum number of unavailable pods during updates
